services:

  app:
    build: .
    restart: unless-stopped
    depends_on:
     db:
       condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - APP_DB_CONNECTION_STRING=root:efraim@tcp(db:3306)/point?charset=utf8mb4&parseTime=True&loc=Local
      - APP_PORT=8080

  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=point
      - MYSQL_ROOT_PASSWORD=efraim
      

    healthcheck:
       test: ["CMD", "mysql", "-u", "root",  "-pefraim", "-e", "show schemas"]
       interval: 20s 
